<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Terms of Service - WebCraft Studio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css" rel="stylesheet">
    <style>
        body { font-family: system-ui, -apple-system, 'Segoe UI', sans-serif; color: #1e293b; line-height: 1.7; }
        .policy-content h2 { font-size: 1.3rem; font-weight: 700; margin-top: 2rem; color: #0f172a; }
        .policy-content p, .policy-content li { font-size: 15px; color: #334155; }
        .policy-content ul { padding-left: 1.5rem; }
        .policy-content li { margin-bottom: 0.5rem; }
        .top-bar { background: #0f172a; color: #fff; padding: 12px 0; }
        .top-bar .brand { font-weight: 600; font-size: 16px; }
        .footer-bar { background: #0f172a; color: #94a3b8; text-align: center; padding: 12px; font-size: 11px; margin-top: 40px; }
    </style>
</head>
<body>
<div class="top-bar">
    <div class="container d-flex align-items-center justify-content-between">
        <span class="brand">WebCraft Studio</span>
        <a href="/" class="btn btn-sm btn-outline-light"><i class="bi bi-arrow-left"></i> Back to Home</a>
    </div>
</div>

<div class="container py-5" style="max-width:800px;">
    <h1 class="fw-bold mb-2">Terms of Service</h1>
    <p class="text-muted mb-4">Last updated: September 13, 2026</p>

    <div class="policy-content">
        <h2>1. Acceptance of Terms</h2>
        <p>By accessing and using WebCraft Studio&rsquo;s Website Requirement &amp; Quotation System, you agree to be bound by these Terms of Service. If you do not agree, please do not use our service.</p>

        <h2>2. Service Description</h2>
        <p>WebCraft Studio provides an online platform for:</p>
        <ul>
            <li>Collecting website project requirements through a structured form.</li>
            <li>Generating automated price estimates based on selected features.</li>
            <li>Creating and delivering project quotations.</li>
        </ul>

        <h2>3. Quotation Accuracy</h2>
        <p>All price estimates generated by our system are <strong>indicative only</strong>. Final pricing may vary after:</p>
        <ul>
            <li>Detailed requirement verification by our team.</li>
            <li>Design and technical assessment.</li>
            <li>Project scope confirmation and clarification.</li>
        </ul>
        <p>A formal quotation will be provided after our team reviews your submitted requirements.</p>

        <h2>4. User Responsibilities</h2>
        <p>When using our service, you agree to:</p>
        <ul>
            <li>Provide accurate and truthful information.</li>
            <li>Not submit spam, fake, or malicious data.</li>
            <li>Maintain the confidentiality of your project details.</li>
        </ul>

        <h2>5. Intellectual Property</h2>
        <p>All content, design, and code on this platform are the property of WebCraft Studio. You retain full ownership of your project ideas and requirements submitted through our system.</p>

        <h2>6. Limitation of Liability</h2>
        <p>WebCraft Studio shall not be liable for any indirect, incidental, or consequential damages arising from the use of our quotation system. The automated estimate is a tool to assist in budgeting, not a binding contract.</p>

        <h2>7. Changes to Terms</h2>
        <p>We reserve the right to update these terms at any time. Changes will be posted on this page with an updated date. Continued use of the service constitutes acceptance of the new terms.</p>

        <h2>8. Governing Law</h2>
        <p>These terms are governed by the laws of Nepal. Any disputes shall be resolved in the courts of Kathmandu, Nepal.</p>
    </div>
</div>

<div class="footer-bar">
    &copy; 2026 WebCraft Studio. All rights reserved. | Built by <strong style="color:#e2e8f0;">Abhijeet Prajapati</strong>
</div>
</body>
</html>
